name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service
    defaults:
      run:
        working-directory: ${{env.working-directoy}}
      steps:
        - uses: actions/checkout@v4

        - name: Setup Java 21
          uses: actions/setup-java@4
          with:
            java-version: '21'
            cache: 'maven'

        - name: Build With Maven
          run: ./mvn -ntp verify
